### ISSUE TITLE
A question about the opening move in the self-play games of v1.3

### ISSUE THREAD

**Issue by sbbdms** [kobanium/aoba-zero#11]
Hi!
After v1.3 released, I generated 28 self-play games and when I observe the .csa files, I found that for the 1st move, 2726FU has the highest playouts in all the 28 games. However, AobaZero selects 7776FU in 4 games and 3938GI in other 24 games --- 2726FU is never selected when it always has the highest playouts. This phenomenon is totally different from v1.2.
Is this a feature caused by the recently implemented tree-reuse?
[csa.zip](https://github.com/kobanium/aobazero/files/3369121/csa.zip)

**Comment by yssaya** [comment]
Thanks! It is bug random  seed is constant for visit count sampling.
We will fix and update v1.4 soon.

**Comment by sbbdms** [comment]
Thanks! (Closing after v1.4 released)
