### ISSUE TITLE
BNZ_NAME を変更したい

### ISSUE THREAD

**Issue by topstone** [kobanium/aoba-zero#57]
有用な成果物を公開していただき、ありがとうございます。

AobaZero v1.9 なのに将棋所では「AobaZero 15」と認識され、私は最初混乱しました。

src/usi-engine/bona/shogi.h の122-123行目辺りで定義されているので version ではない何らかの意味があるのだろうと推測しますが、これを aobaz.bat からの起動 option で変更できるようにできませんでしょうか。具体的には以下のような感じです。

`bin\aobaz --name=AobaZero_1.9_w2184 -q -i -p 100 -w weight-save\w000000002184.txt`

将棋所上で AobaZero 同士の対局を行わせたいので、表示名を手軽に変更できると助かります。

**Comment by yssaya** [comment]
ご指摘のように、バージョンと共に重み番号もnameに入ってると便利だと思います。
リリースを作るのは少し大変なのでnameを変更できるバイナリを作ってみました。OpenCL用です。
これをbin の下に置いて
bin\aobaz20210920 -name AobaZero_1.9_w2184 -q -i -p 100 -w weight-save\w000000002184.txt
で変更可能です。名前の途中にスペースを入れると動作しなくなります。

http://www.yss-aya.com/aobazero/aobaz20210920.zip

**Comment by topstone** [comment]
素早い対応ありがとうございます。

実は貧弱な PC で実行していまして、OpenCL 版が動かない環境です。お手数でなければ cpu-only 版を作っていただけると嬉しいのですが、お手数でしたら次の release までお待ちします。

--------

以下、本来は私自身が解決しなければならない問題なので、無視していただいて結構です。

Intel UHD Graphics 600 に最新の driver ([30.0.100.9894; 2021-09-08](https://www.intel.com/content/www/us/en/search.html?ws=text#t=Downloads&layout=table&cf:Downloads=[%7B%22actualLabel%22%3A%22Graphics%22%2C%22displayLabel%22%3A%22Graphics%22%7D%2C%7B%22actualLabel%22%3A%22Intel%C2%AE%20UHD%20Graphics%20Family%22%2C%22displayLabel%22%3A%22Intel%C2%AE%20UHD%20Graphics%20Family%22%7D%2C%7B%22actualLabel%22%3A%22Intel%C2%AE%20UHD%20Graphics%20600%22%2C%22displayLabel%22%3A%22Intel%C2%AE%20UHD%20Graphics%20600%22%7D])) を入れています。[Intel UHD Graphics 600 は OpenCL 3.0 対応らしい](https://www.techpowerup.com/gpu-specs/uhd-graphics-600.c3065)のですが、AobaZero の OpenCL 版は動きませんでした。Windows 10 (64-bit) 21H1, DirectX12 です。

この環境で OpenCL 版が動かない理由をもしご存知でしたら、ご教示いただけると幸いです。

**Comment by yssaya** [comment]
CPU版をこちらに置きました。
http://www.yss-aya.com/aobazero/aobaz20210921cpu.zip

OpenCL版が動かない原因は分かりませんが、以下の方法で動くかもしれません。
aobazero-1.9-w64-opencl.zipに含まれる、
opencl-icd-loader\v2.2.1\OpenCL.dll
この OpenCL.dll を
bin
の下に(aobaz.exeがあるディレクトリと同じ場所)にコピーしてみてください。

これでも動かない場合は下のコピーもお試しください。
opencl-icd-loader\v25.20.14012\OpenCL.dll

**Comment by topstone** [comment]
ご対応ありがとうございます。

OpenCL.dll については、どちらもうまくいきませんでした。

私は cpu-only 版でも用が足りますので、こちらを使わせていただきます。ありがとうございました。
